# Generated by Django 4.2.4 on 2023-08-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='person',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
