# Generated by Django 4.2.4 on 2023-08-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_remove_person_groups_remove_person_user_permissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='email',
            new_name='username',
        ),
    ]
