# Generated by Django 4.2.4 on 2023-09-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_rename_email_person_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(default='Front end developer', max_length=200),
            preserve_default=False,
        ),
    ]
