# Generated by Django 4.2.4 on 2023-09-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_person_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default='Sari', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='university',
            field=models.CharField(default='Sari', max_length=200),
            preserve_default=False,
        ),
    ]
