# Generated by Django 4.2.4 on 2023-09-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0005_person_address_person_university"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
