# Generated by Django 3.2 on 2024-01-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20231006_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='activation_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
