# Generated by Django 3.2 on 2024-01-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_person_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='activation_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
