# Generated by Django 3.2 on 2024-01-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_auto_20240109_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
