# Generated by Django 4.2.4 on 2023-09-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="years",
            field=models.CharField(max_length=4),
        ),
    ]
